In [4]:
import pandas as pd
import numpy as np
import nltk

from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\dell\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [5]:
import pandas as pd
import numpy as np
import nltk

from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\dell\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [6]:
fake = pd.read_csv("dataset/Fake.csv")
true = pd.read_csv("dataset/True.csv")

In [7]:
fake.head()

,title,text,subject,date
0,Donald Trump Sends Out Embarrassing New Year’s...,Donald Trump just couldn t wish all Americans ...,News,"December 31, 2017"
1,Drunk Bragging Trump Staffer Started Russian C...,House Intelligence Committee Chairman Devin Nu...,News,"December 31, 2017"
2,Sheriff David Clarke Becomes An Internet Joke ...,"On Friday, it was revealed that former Milwauk...",News,"December 30, 2017"
3,Trump Is So Obsessed He Even Has Obama’s Name ...,"On Christmas day, Donald Trump announced that ...",News,"December 29, 2017"
4,Pope Francis Just Called Out Donald Trump Duri...,Pope Francis used his annual Christmas Day mes...,News,"December 25, 2017"

In [8]:
true.head()

,title,text,subject,date
0,"As U.S. budget fight looms, Republicans flip t...",WASHINGTON (Reuters) - The head of a conservat...,politicsNews,"December 31, 2017"
1,U.S. military to accept transgender recruits o...,WASHINGTON (Reuters) - Transgender people will...,politicsNews,"December 29, 2017"
2,Senior U.S. Republican senator: 'Let Mr. Muell...,WASHINGTON (Reuters) - The special counsel inv...,politicsNews,"December 31, 2017"
3,FBI Russia probe helped by Australian diplomat...,WASHINGTON (Reuters) - Trump campaign adviser ...,politicsNews,"December 30, 2017"
4,Trump wants Postal Service to charge 'much mor...,SEATTLE/WASHINGTON (Reuters) - President Donal...,politicsNews,"December 29, 2017"

In [9]:
fake["classes"]=0
true["classes"]=1

In [10]:
fake.tail()

,title,text,subject,date,classes
13834,ILLEGAL ALIENS Sent To States With Lax Voter I...,DEMOCRATS Making free and fair elections impos...,politics,"May 25, 2016",0
13835,BREAKING! INVESTIGATION: Hillary Clinton Did N...,Was Hillary Clinton negligent or was she doin...,politics,"May 25, 2016",0
13836,DEMOCRAT UNDERBELLY EXPOSED: Out-Of-Control Vi...,Donald Trump on Wednesday slammed what he desc...,politics,"May 25, 2016",0
13837,DESPERATION OR STUPIDITY? GERMAN State Recruit...,It s too late for these countries who ve been ...,politics,"May 25, 2016",0
13838,WATCH: Black Lives Matter Terrorists CRASH Sta...,It s hard to tell what these Black Lives Matte...,politics,"May 25, 2016",0

In [12]:
true.tail()

,title,text,subject,date,classes
6744,Green Party U.S. election recount bid comes to...,(Reuters) - The recount effort by Green Party ...,politicsNews,"December 12, 2016",1
6745,China warns Trump against ignoring its Taiwan ...,BEIJING (Reuters) - China expressed “serious c...,politicsNews,"December 12, 2016",1
6746,Trump attack on Lockheed Martin foreshadows wa...,SEATTLE (Reuters) - Donald Trump on Monday wid...,politicsNews,"December 12, 2016",1
6747,Senate Republican leader backs investigation i...,WASHINGTON (Reuters) - The Senate’s top Republ...,politicsNews,"December 12, 2016",1
6748,Trump taps Goldman Sachs executive Cohn for ke...,WASHINGTON (Reuters) - U.S. President-elect Do...,politicsNews,"December 12, 2016",1

In [14]:
data=pd.concat([fake,true],axis=0)

In [15]:
data = data.sample(frac=1)

In [16]:
data.reset_index(inplace=True)

In [17]:
data.drop(["index"],axis=1,inplace=True)

In [18]:
data.head()

,title,text,subject,date,classes
0,Another White Guy Goes On A Shooting Spree And...,"Six people are dead after a white, domestic te...",News,"February 21, 2016",0
1,Trump may not enforce individual health insura...,WASHINGTON (Reuters) - The Trump administratio...,politicsNews,"January 22, 2017",1
2,GOP Puts Together Secret Talking Points To Def...,The Trump White House is perhaps the leakiest ...,News,"June 15, 2017",0
3,U.S. attorney general calls for efficient revi...,WASHINGTON (Reuters) - U.S. Attorney General J...,politicsNews,"December 6, 2017",1
4,"Obama says he would have outrun Trump, but Tru...",HONOLULU (Reuters) - U.S. President Barack Oba...,politicsNews,"December 27, 2016",1

In [19]:
data.shape

(20588, 5)

In [20]:
data.isnull().sum()

title        0
text       371
subject      0
date         0
classes      0
dtype: int64

In [21]:
data.columns

Index(['title', 'text', 'subject', 'date', 'classes'], dtype='object')

In [22]:
data = data.drop(["title", "subject", "date"], axis=1)

In [23]:
data.head()

                                                text  classes
0  Six people are dead after a white, domestic te...        0
1  WASHINGTON (Reuters) - The Trump administratio...        1
2  The Trump White House is perhaps the leakiest ...        0
3  WASHINGTON (Reuters) - U.S. Attorney General J...        1
4  HONOLULU (Reuters) - U.S. President Barack Oba...        1

In [24]:
import re 
import string

In [25]:
def wordopt(text):
    text = text.lower()
    text = re.sub(r'\[.*?\]', '', text)
    text = re.sub(r'https?://\S+|www\.\S+', '', text)
    text = re.sub(r'<.*?>+', '', text)
    text = re.sub(r'[%s]' % re.escape(string.punctuation), '', text)
    text = re.sub(r'\n', '', text)
    text = re.sub(r'\w*\d\w*', '', text)
    return text

In [26]:
data= data.dropna()

In [27]:
data["text"] = data["text"].apply(wordopt)

In [28]:
data.head()

                                                text  classes
0  six people are dead after a white domestic ter...        0
1  washington reuters  the trump administration m...        1
2  the trump white house is perhaps the leakiest ...        0
3  washington reuters  us attorney general jeff s...        1
4  honolulu reuters  us president barack obama sa...        1

In [29]:
x = data["text"]
y = data["classes"]

In [30]:
x_train, x_test, y_train, y_test = train_test_split(
    x, y, test_size=0.25, random_state=42
)

In [31]:
vectorization = TfidfVectorizer()
xv_train = vectorization.fit_transform(x_train)
xv_test = vectorization.transform(x_test)

In [32]:
LR = LogisticRegression()
LR.fit(xv_train, y_train)

LogisticRegression()

In [33]:
pred_lr = LR.predict(xv_test)

In [34]:
accuracy_score(y_test,pred_lr)

0.9798219584569733

In [35]:
from sklearn.metrics import classification_report

print(classification_report(y_test, pred_lr))

              precision    recall  f1-score   support

           0       0.98      0.99      0.99      3404
           1       0.98      0.96      0.97      1651

    accuracy                           0.98      5055
   macro avg       0.98      0.98      0.98      5055
weighted avg       0.98      0.98      0.98      5055

In [36]:
from sklearn.metrics import confusion_matrix

print(confusion_matrix(y_test, pred_lr))

[[3366   38]
 [  64 1587]]

In [37]:
from sklearn.metrics import confusion_matrix

print(confusion_matrix(y_test, pred_lr))

[[3366   38]
 [  64 1587]]

In [38]:
from sklearn.tree import DecisionTreeClassifier

In [39]:
DT  = DecisionTreeClassifier()
DT.fit(xv_train, y_train)

DecisionTreeClassifier()

In [40]:
pred_dt = DT.predict(xv_test)

In [41]:
accuracy_score(y_test,pred_dt)

0.9972304648862512

In [42]:
from sklearn.ensemble import RandomForestClassifier

In [43]:
RF = RandomForestClassifier(random_state=42)
RF.fit(xv_train, y_train)

RandomForestClassifier(random_state=42)

In [44]:
pred_rf = RF.predict(xv_test)

In [45]:
accuracy_score(y_test,pred_rf)

0.9780415430267062

In [46]:
from sklearn.ensemble import GradientBoostingClassifier

In [47]:
GB = GradientBoostingClassifier(random_state=42)
GB.fit(xv_train, y_train)

GradientBoostingClassifier(random_state=42)

In [48]:
pred_gb = GB.predict(xv_test)

In [49]:
def manual_testing(news):

    testing_news = {"text": [news]}
    new_def_test = pd.DataFrame(testing_news)

    new_def_test["text"] = new_def_test["text"].apply(wordopt)

    new_x_test = vectorization.transform(new_def_test["text"])

    pred_LR = LR.predict(new_x_test)

    return output_label(pred_LR[0])

In [ ]:
news = str(input())
manual_testing(news)

In [54]:
import pickle

pickle.dump(LR, open("model/logistic_model.pkl", "wb"))
pickle.dump(vectorization, open("model/vectorizer.pkl", "wb"))

In [56]:
import os 
os.listdir("model")

['logistic_model.pkl', 'vectorizer.pkl']